version: "3"

services: 
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./src:/src/app
    environment:
     - REACT_APP_NAME=ThePICARD
     - CHOKIDAR_USEPOLLING=true
